version: "3.2"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: codex
      POSTGRES_DB: codex
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres: